In [23]:
#array

enflish_marks=[10,20,30,40,50]
french_marks=[20,30,40,50,60]

#2d-array
marks=[[10,20],[20,30],[30,40],[40,50],[50,60]]

# for i in enflish_marks:
#     print(i)


for i in marks:
    print(i)

[10, 20]
[20, 30]
[30, 40]
[40, 50]
[50, 60]


In [24]:
import numpy as np

marks=[10,20,30,40,50]

marks=np.array(marks)

my_marks=np.array([10,20,30,40,50])

my_marks

array([10, 20, 30, 40, 50])

In [25]:
marks=np.array([10,20,30,40,50])
print(marks.shape)

print(marks.ndim) #NUMBER OF DIMENSION
print(marks.size) #NUMBER OF ELEMENTS

print(marks.dtype) #DATA TYPE


(5,)
1
5
int64


In [26]:
all_marks=np.array([[10,20,30,40],[40,50,60,70],[70,80,90,100]])

print(all_marks)
print(all_marks.shape)
print(all_marks.ndim)
print(all_marks.size)

[[ 10  20  30  40]
 [ 40  50  60  70]
 [ 70  80  90 100]]
(3, 4)
2
12


In [27]:
my_arr=np.zeros((3,2))
print(my_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [28]:
my_arr=np.ones((3,2))
print(my_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [29]:
print(my_arr.dtype)
my_arr= my_arr.astype(int) #change the data type
print(my_arr.dtype)

float64
int64


In [31]:
marks=[10,20,30,40,50]
print(marks[1])

marks=np.array([10,20,30,40,50])
print(marks[1])

20
20


In [37]:
all_marks=([[10,20,30,40],[40,50,60,70],[70,80,90,100]])
print(all_marks[1][1])
print(all_marks[2][2])


all_marks=np.array([[10,20,30,40],[40,50,60,70],[70,80,90,100]])
print(all_marks[1,1])
print(all_marks[2,2])



50
90
50
90


In [42]:
marks=[10,20,30,40,50]

print(marks[:3])
print(marks[2:])
print(marks[1:4])




[10, 20, 30]
[30, 40, 50]
[20, 30, 40]


In [43]:
marks=np.array([10,20,30,40,50])
print(marks[:3])

[10 20 30]


In [51]:
all_marks=np.array([[10,20,30,40],[40,50,60,70],[70,80,90,100]])
print(all_marks[:])

print(all_marks[:2,:2])

print(all_marks[:2,:2])



[[ 10  20  30  40]
 [ 40  50  60  70]
 [ 70  80  90 100]]
[[10 20]
 [40 50]]
[[10 20]
 [40 50]]


In [54]:
print(all_marks[1:,2:])

[[ 60  70]
 [ 90 100]]


In [59]:
array=np.array([10,20,30,40,50])
print(array[::-1])

all_marks=np.array([[10,20,30,40],[40,50,60,70],[70,80,90,100]])
print(all_marks)
print(all_marks[::-1,::-1])

[50 40 30 20 10]
[[ 10  20  30  40]
 [ 40  50  60  70]
 [ 70  80  90 100]]
[[100  90  80  70]
 [ 70  60  50  40]
 [ 40  30  20  10]]


In [100]:
sequence=np.arange(10,21)
print(sequence)

sequence=np.arange(1,10,2)
print(sequence)

split=np.linspace(0,10,5)
print(split)

random=np.random.rand(2,2)
print(random)

[10 11 12 13 14 15 16 17 18 19 20]
[1 3 5 7 9]
[ 0.   2.5  5.   7.5 10. ]
[[0.2215001  0.62029152]
 [0.10843132 0.03573678]]


In [134]:
random_integers = np.random.randint(0, 41, 6)

print(random_integers) # [5, 1, 2, 7, 3]

[14 34 31  2 19  5]


In [136]:
marks=np.array([10,20,30,40,50,60])
print(marks.reshape(3,2))
print(marks.reshape(2,3))



[[10 20]
 [30 40]
 [50 60]]
[[10 20 30]
 [40 50 60]]


In [137]:
test=np.eye(4)
test

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [139]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

print(matrix[1])




[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]


In [147]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

print('----')
print(matrix[:,2:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----
[[3]
 [6]
 [9]]


In [150]:
marks=np.array([10,20,30,40,50,60])
print(marks+10)
print(marks-10)
print(marks*2)

[20 30 40 50 60 70]
[ 0 10 20 30 40 50]
[ 20  40  60  80 100 120]


In [151]:
marks=np.array([10,20,30,40,50,60])
marks2=np.array([5,6,7,8,9,10])

marks3=marks+marks2
print(marks3)

[15 26 37 48 59 70]


In [154]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix)

print('----')
print(matrix+matrix2)
print(matrix*matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [156]:
matrix3=matrix*matrix2
print(matrix3)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [164]:
print(matrix3.mean())  
print(matrix3.max())  
print(matrix3.min())
print(matrix3.sum())
print(matrix3-matrix.mean())

31.666666666666668
81
1
285
[[-4. -1.  4.]
 [11. 20. 31.]
 [44. 59. 76.]]


In [168]:
matrix2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix2[[2,0]]=matrix2[[0,2]]
print(matrix2)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [179]:
marks=np.array([10,20,30,40,50,60])

print(marks.mean())

print(np.mean(marks))

print(np.median(marks))

print(np.sqrt(matrix3))



35.0
35.0
35.0
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [180]:
print(np.sqrt.__doc__)

sqrt(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the non-negative square-root of an array, element-wise.

Parameters
----------
x : array_like
    The values whose square-roots are required.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``, locations within it where the condition is False will
    remain uni

In [189]:
data=np.array([[1,0,2],[1,0,0],[0,0,1]])
print(data)

# print(data.nonzero())
print(np.nonzero(data))




[[1 0 2]
 [1 0 0]
 [0 0 1]]
(array([0, 0, 1, 2]), array([0, 2, 0, 2]))


In [191]:
data=np.array([0,1,2,0,3,100,0])

print(data.nonzero())

(array([1, 2, 4, 5]),)


In [193]:
array=np.array([2,4,4,1,3,5,0,0])

print(np.bincount(array))   

[2 1 1 1 2 1]


In [195]:
bincount=np.bincount(array)
recreated_array = np.repeat(np.arange(len(bincount)), bincount)
print(recreated_array)
print(sorted(array))



[0 0 1 2 3 4 4 5]
[0, 0, 1, 2, 3, 4, 4, 5]
